apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: "temd"
  namespace: argocd
spec:
  source:
    sourceRepos:
      - '*'
    destinations:
      - namespace: '*'
        server: '*'
    clusterResourceWhitelist:
      - group: '*'
        kind: '*'
    helm:
      parameters : "temd"

